### ISSUE TITLE
Error during install: 'unknown configuration section 'hostmanager'.'

### ISSUE THREAD

**Issue by UncleRedBeard** [TobyHFerguson/Davenport#38]
running 'vagrant up' with everything in place yields the following error

> Script started on Tue 21 Apr 2015 06:32:12 PM CDT
> Bringing machine 'oemrepo' up with 'virtualbox' provider...
> Bringing machine 'oms' up with 'virtualbox' provider...
> Bringing machine 'dhcp' up with 'virtualbox' provider...
> Bringing machine 'stage' up with 'virtualbox' provider...
> Bringing machine 'tftp' up with 'virtualbox' provider...
> Bringing machine 'yum' up with 'virtualbox' provider...
> There are errors in the configuration of this machine. Please fix
> the following errors and try again:
> 
> Vagrant:
> - Unknown configuration section 'hostmanager'.
> 
> Script done on Tue 21 Apr 2015 06:32:15 PM CDT

**Comment by TobyHFerguson** [comment]
Did you install the plugins as mentioned in the README: https://github.com/TobyHFerguson/Davenport#vagrant-plugins

**Comment by UncleRedBeard** [comment]
i did, but apparently they did not install properly.

'vagrant plugin list' only showed vagrant-share (1.1.3, system).

installed each plugin manually and restarted 'vagrant up'

now 'vagrant plugin list' shows
- vagrant-hostmanager (1.5.0)
- vagrant-multiprovider-snap (0.0.14)
- vagrant-share (1.1.3, system)
- vagrant-vbguest (0.10.0)

running 'vagrant up' again

**Comment by UncleRedBeard** [comment]
re-installing the plugins fixed the issue. i must have misspelled one of the plugins' names
